n = input('Quem e a nossa cobaia?')
print('Que tipo e a nossa cobaia?', type(n))
print('Nossa cobaia tem espaco?', n.isspace())
print('Nossa cobaia e um numero?', n.isnumeric())
print('Nossa cobaia e alfabetica?', n.isalpha())
print('Nossa cobaia e alfanumerico?', n.isalnum())
print('Nossa cobaia edta em Maisculo?', n.isupper())
print('Nossa cobaia esta em minusculo?', n.islower())
print('Nossa cobaia esta capitalizada?', n.istitle())
